/*
 * account-service
 * api.description
 *
 * OpenAPI spec version: 1.0
 * Contact: api@demo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package s.core.dd.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import s.core.dd.model.AccountType;
import s.core.dd.model.Customer;
import javax.validation.constraints.*;

/**
 * Represents an account of the system
 */
@ApiModel(description = "Represents an account of the system")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2020-08-26T19:48:20.668+05:30")
public class Account   {
  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("number")
  private String number = null;

  @JsonProperty("type")
  private AccountType type = null;

  @JsonProperty("balance")
  private Double balance = null;

  @JsonProperty("customer")
  private Customer customer = null;

  @JsonProperty("allow_scheduled_transactions")
  private String allowScheduledTransactions = null;

  public Account id(Integer id) {
    this.id = id;
    return this;
  }

  /**
   * The ID of the account
   * @return id
   **/
  @JsonProperty("id")
  @ApiModelProperty(required = true, value = "The ID of the account")
  @NotNull
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Account number(String number) {
    this.number = number;
    return this;
  }

  /**
   * The account number
   * @return number
   **/
  @JsonProperty("number")
  @ApiModelProperty(required = true, value = "The account number")
  @NotNull
  public String getNumber() {
    return number;
  }

  public void setNumber(String number) {
    this.number = number;
  }

  public Account type(AccountType type) {
    this.type = type;
    return this;
  }

  /**
   * The account type
   * @return type
   **/
  @JsonProperty("type")
  @ApiModelProperty(required = true, value = "The account type")
  @NotNull
  public AccountType getType() {
    return type;
  }

  public void setType(AccountType type) {
    this.type = type;
  }

  public Account balance(Double balance) {
    this.balance = balance;
    return this;
  }

  /**
   * The account balance
   * @return balance
   **/
  @JsonProperty("balance")
  @ApiModelProperty(required = true, value = "The account balance")
  @NotNull
  public Double getBalance() {
    return balance;
  }

  public void setBalance(Double balance) {
    this.balance = balance;
  }

  public Account customer(Customer customer) {
    this.customer = customer;
    return this;
  }

  /**
   * The customer holding the account
   * @return customer
   **/
  @JsonProperty("customer")
  @ApiModelProperty(required = true, value = "The customer holding the account")
  @NotNull
  public Customer getCustomer() {
    return customer;
  }

  public void setCustomer(Customer customer) {
    this.customer = customer;
  }

  public Account allowScheduledTransactions(String allowScheduledTransactions) {
    this.allowScheduledTransactions = allowScheduledTransactions;
    return this;
  }

  /**
   * The flag representing if scheduled transactions are allowed
   * @return allowScheduledTransactions
   **/
  @JsonProperty("allow_scheduled_transactions")
  @ApiModelProperty(required = true, value = "The flag representing if scheduled transactions are allowed")
  @NotNull
  public String getAllowScheduledTransactions() {
    return allowScheduledTransactions;
  }

  public void setAllowScheduledTransactions(String allowScheduledTransactions) {
    this.allowScheduledTransactions = allowScheduledTransactions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Account account = (Account) o;
    return Objects.equals(this.id, account.id) &&
        Objects.equals(this.number, account.number) &&
        Objects.equals(this.type, account.type) &&
        Objects.equals(this.balance, account.balance) &&
        Objects.equals(this.customer, account.customer) &&
        Objects.equals(this.allowScheduledTransactions, account.allowScheduledTransactions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, number, type, balance, customer, allowScheduledTransactions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Account {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    balance: ").append(toIndentedString(balance)).append("\n");
    sb.append("    customer: ").append(toIndentedString(customer)).append("\n");
    sb.append("    allowScheduledTransactions: ").append(toIndentedString(allowScheduledTransactions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

