swagger: '2.0'
info:
  description: api.description
  version: '1.0'
  title: account-service
  termsOfService: api.termsOfService
  contact:
    name: api.contact.name
    url: 'http://api.contact.url'
    email: api@demo.com
  license:
    name: api.license.name
    url: 'http://api.license.url'
host: '0.0.0.0:9988'
basePath: /account-service/1.0
schemes:
  - http
paths:
  /accounts:
    get:
      operationId: getAccounts
      summary: Find all accounts
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: user
          in: query
          description: account holder
          required: true
          type: string
      responses:
        '200':
          description: All accounts successfully returned
          schema:
            type: array
            items:
              $ref: '#/definitions/Account'
  '/accounts/{id}':
    get:
      operationId: getAccount
      summary: Find account by ID
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: The ID of the account
          required: true
          type: integer
      responses:
        '200':
          description: account successfully returned
          schema:
            $ref: '#/definitions/Account'
definitions:
  Account:
    type: object
    required:
      - allow_scheduled_transactions
      - balance
      - customer
      - id
      - number
      - type
    properties:
      id:
        type: integer
        format: int32
        description: The ID of the account
      number:
        type: string
        description: The account number
      type:
        description: The account type
        $ref: '#/definitions/AccountType'
      balance:
        type: number
        format: double
        description: The account balance
      customer:
        description: The customer holding the account
        $ref: '#/definitions/Customer'
      allow_scheduled_transactions:
        type: string
        description: The flag representing if scheduled transactions are allowed
    description: Represents an account of the system
    x-className:
      type: string
      format: demo.bank.core.account.model.Account
  Customer:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: integer
        format: int32
        description: The ID of the customer
      name:
        type: string
        description: The name of the customer
    description: Represents a customer of the system
  AccountType:
    type: object
    required:
      - description
      - id
    properties:
      id:
        type: integer
        format: int32
        description: The ID of the account type
      description:
        type: string
        description: The description of the account type
    description: Represents an account type of the system
